Refactor Project
zaanposni/vvspy pull request #59
Opened 2022-11-17 14:15 UTC by felixhoffmnn

## Description

This PR includes potential **breaking changes**!

- 

## Test Plan

## Commentary (optional)

## Checklist

- [ ] Connected regarding _GitHub issues_ and _discussions_
- [ ] Added _docstrings_ for all new functions
- [ ] Checked _CI_ pipeline for any failures
- [ ] Run _pytests_ locally to check for any failures

2022-11-17 17:01 UTC, felixhoffmnn commented on .github/CODEOWNERS
> +\*.py @zaanposni
Needs to be fixed

2022-11-17 17:02 UTC, felixhoffmnn commented on docs/vvspy/functions.md
> +# VVSPY Function Documentation
Add text

2022-11-17 17:58 UTC, felixhoffmnn commented on docs/vvspy/models.md
> +
Add text

2022-11-17 17:58 UTC, felixhoffmnn commented on docs/vvspy/utils.md
> +
Add text

2022-11-19 14:47 UTC, zaanposni requested changes

2022-11-19 14:47 UTC, zaanposni commented on vvspy/trips.py
> +        print(result["journeys"])
did you mean to add debugging here or did you forget to remove that print statement ^.^ ?

```suggestion
```

2022-11-19 14:47 UTC, zaanposni commented on .github/CODEOWNERS
> +\*.py @zaanposni
We can add you as a codeowner too if you want to

2022-11-19 14:54 UTC, zaanposni commented on .github/workflows/pytest.yaml
> +    branches: ["main"]
For now vvspy uses "master" as default branch. 
We can change that later on.
For now please change it here, so we can test your workflows.

2022-11-19 18:11 UTC, felixhoffmnn commented on .github/workflows/pytest.yaml
> +    branches: ["main"]
Ah I see. Did not notice it in dev.

2022-11-19 18:21 UTC, felixhoffmnn commented on .github/CODEOWNERS
> +\*.py @zaanposni
For now, I will only change the syntax.

2024-01-16 17:24 UTC, closed without merging